# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NOn7Q2PYiOYsYu5_3cHnmikFnT-ESrEJ

#Day 2, python 200 hours

##1. Struktur data

```
int   : 1, 3, 5, 9, -3, 0             # bilangan integer (bulat)
float : 1.0, 0.9, -0.7, 5.6, 8.0      # bilangan desimal
str   : "hello", "0.2", '-98', 'True' # huruf alfabet/sebuah pernyataan
bool  :True, False                    # bilangan untuk kondisi true/false
```
"""

x = 5
y = 6

d = 12 % 5    # d is 2
z = x + y     # z is 11
w = x - y     # w is -1
q = 5 * 6     # q is 30
u = 10 / x    # u is 2.0
p = 10 * 2.0  # p is 20.0
t = x ** 3    # t is 125
c = 28 // y   # c is 4

d, z, w, q, u, p, t, c

"""

```
<   # less than
<=  # less than or equal to
>   # greater than
>=  # greater than or equal to
==  # equal to
!=  # not equal to
```

"""

x = 5
y = 9

x > y       # This is False
y == x      # This is False
x < y - 1   # This is True
x + 1 != y  # This is True
2.0 > 5     # This is False

"hello" == "hello"  # This is True, kata sama
"tim" == "Tim"      # This is False, kata sama, namun yg satu menggunakan kapital
"a" > "b"           # This is False, sesuai urutan alphabet
"apple" < "tim"     # This is False, sesuai banyaknya huruf

"""##2. Dokumentasi math di Py"""

from math import pi
# from math import sub, sub tidak ada
from math import pow
from math import log
from math import sqrt

"""###contoh penggunaan"""

from math import pi
def hitung_luas_lingkaran(jari_jari):
  luas = pi * (jari_jari ** 2)
  return luas

# Contoh penggunaan
jari_jari = 5
luas = hitung_luas_lingkaran(jari_jari)
print("Luas lingkaran dengan jari-jari", jari_jari, "adalah:", luas)

"""##3. Fungsi definition"""

def penjumlahan (x, y):
  return pow(x, y)
|print(penjumlahan(10,5))

